Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      ImageId: 'ami-5e8bb23b'
      InstanceType: 't2.large'
      KeyName: 'yourKey'
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash -ex
             curl https://raw.githubusercontent.com/valancej/Anchore-Engine-Cloudformation/master/scripts/anchoreInstall.sh -o anchoreInstall.sh;
             chmod +x anchoreInstall.sh;
             ./anchoreInstall.sh
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8228'
          ToPort: '8228'
          CidrIp: 0.0.0.0/0  